import {
  table,
  autoGeneratedHashKey,
  attribute
} from '@aws/dynamodb-data-mapper-annotations';

@table('bookmarks')
class BookmarkModel {
  @autoGeneratedHashKey()
  id: string;

  @attribute({ memberType: { type: 'String' } })
  links: Array<string>;
}

export default BookmarkModel;
